# Use the official nginx base image
FROM nginx:alpine

# Copy your static files into the nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80
# EXPOSE 80

# Nginx will run automatically
